# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/M10702114/ntust_HSCodesign_et5342701/fpga/barrage_game/barrage_game.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
# IP: The module: 'system_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/M10702114/ntust_HSCodesign_et5342701/fpga/barrage_game/barrage_game.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: e:/M10702114/ntust_HSCodesign_et5342701/fpga/barrage_game/barrage_game.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
# IP: The module: 'system_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/M10702114/ntust_HSCodesign_et5342701/fpga/barrage_game/barrage_game.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
